# Generated by Django 4.2.7 on 2023-12-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('t_id', models.IntegerField(default='', primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='img')),
                ('place_name', models.CharField(max_length=50)),
            ],
        ),
    ]
