# Generated by Django 4.2.6 on 2023-12-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0003_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
