# Generated by Django 4.2.6 on 2023-12-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0004_delete_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
