# Generated by Django 4.2.6 on 2023-12-22 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourismapp', '0005_travel_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_people', models.PositiveIntegerField(default=0)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourismapp.travel')),
            ],
        ),
    ]
