# Generated by Django 4.2.6 on 2023-12-27 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tourismapp', '0009_rename_date_book_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_people', models.PositiveIntegerField(default=0)),
                ('dates', models.DateField(blank=True, null=True)),
                ('t_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourismapp.travel')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
